### ISSUE TITLE
Feature : Add a save or like option

### ISSUE THREAD

**Issue by unnikrishnan2002** [clubgamma/Random-Meme-Generator-App#31]
It would be nice if a like or save button is added to the mainactivity layout so users can  save/like a meme so that can also view that meme later

**Comment by ak523** [comment]
@unnikrishnan2002 that's a really great idea 👌.

**Comment by unnikrishnan2002** [comment]
Hey @ak523 Can you please unassign me from this issue . Actually, I tried but couldn't make a feasible solution out of it.
Sorry for inconvenience

**Comment by ak523** [comment]
@AasthaSinha2002 share your email id I will share the firebase account details.
Happy coding!🥳

**Comment by AasthaSinha2002** [comment]
You can mail me at – ***@***.***

From: Aryan Kadiya ***@***.***>
Date: Saturday, 9 October 2021 at 11:34 PM
To: clubgamma/Random-Meme-Generator-App ***@***.***>
Cc: AASTHA SINHA ***@***.***>, Mention ***@***.***>
Subject: Re: [clubgamma/Random-Meme-Generator-App] Feature : Add a save or like option (#31)

@AasthaSinha2002<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAasthaSinha2002&data=04%7C01%7C%7Cb53e1f0d98dc4f036d4608d98b4f2d07%7C2c5bdaf48ff24bd9bd547c50ab219590%7C0%7C0%7C637693994444180588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KmhQGQSYXLRB2SKjzxQom9%2Bqi5BIa%2Ft0g18WukXXroQ%3D&reserved=0> share your email id I will share the firebase account details.
Happy coding!🥳

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclubgamma%2FRandom-Meme-Generator-App%2Fissues%2F31%23issuecomment-939337612&data=04%7C01%7C%7Cb53e1f0d98dc4f036d4608d98b4f2d07%7C2c5bdaf48ff24bd9bd547c50ab219590%7C0%7C0%7C637693994444190547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PldyBFtsToEP1Thyzu7WKswH3v9xSlUHSCW%2F6bZh%2BIU%3D&reserved=0>, or unsubscribe<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAR3PYRS2XF6QAZTXZ5ANEKDUGB7Y7ANCNFSM5FOFJM7Q&data=04%7C01%7C%7Cb53e1f0d98dc4f036d4608d98b4f2d07%7C2c5bdaf48ff24bd9bd547c50ab219590%7C0%7C0%7C637693994444190547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=d7eY13z1W%2F8KFrOyMYbsOClRyR%2FC1fa3dnQg8XIpWgA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cb53e1f0d98dc4f036d4608d98b4f2d07%7C2c5bdaf48ff24bd9bd547c50ab219590%7C0%7C0%7C637693994444200500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YRxgQa%2B%2BsbXlYaFhPFUtH9fQmeaW79Cy3SQSHtLkZZ0%3D&reserved=0> or Android<https://ind01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cb53e1f0d98dc4f036d4608d98b4f2d07%7C2c5bdaf48ff24bd9bd547c50ab219590%7C0%7C0%7C637693994444200500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JExrEjv41ZZkvIW2j6op2C9vBXKm9B3dW4E8BEgyWIA%3D&reserved=0>.

**Comment by AasthaSinha2002** [comment]
> @AasthaSinha2002 share your email id I will share the firebase account details. Happy coding!🥳

aasthasinha2010@gmail.com

**Comment by AasthaSinha2002** [comment]
@ak523 please mail me the firebase info at - aasthasinha2010@gmail.com

**Comment by AasthaSinha2002** [comment]
> @AasthaSinha2002 I mailed. You didn't get it?

It went to my spam folder, got it, Thanks !

**Comment by ak523** [comment]
#40 fixes this.
